### ISSUE TITLE
Error: Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by bravemaster619** [duocun/duocun-api#92]
```console
May 18 10:44:47 localhost node[28742]: events.js:174
May 18 10:44:47 localhost node[28742]:       throw er; // Unhandled 'error' event
May 18 10:44:47 localhost node[28742]:       ^
May 18 10:44:47 localhost node[28742]: Error: Client network socket disconnected before secure TLS connection was established
May 18 10:44:47 localhost node[28742]:     at TLSSocket.onConnectEnd (_tls_wrap.js:1088:19)
May 18 10:44:47 localhost node[28742]:     at Object.onceWrapper (events.js:277:13)
May 18 10:44:47 localhost node[28742]:     at TLSSocket.emit (events.js:194:15)
May 18 10:44:47 localhost node[28742]:     at endReadableNT (_stream_readable.js:1103:12)
May 18 10:44:47 localhost node[28742]:     at process._tickCallback (internal/process/next_tick.js:63:19)
May 18 10:44:47 localhost node[28742]: Emitted 'error' event at:
May 18 10:44:47 localhost node[28742]:     at TLSSocket.socketErrorListener (_http_client.js:392:9)
May 18 10:44:47 localhost node[28742]:     at TLSSocket.emit (events.js:189:13)
May 18 10:44:47 localhost node[28742]:     at emitErrorNT (internal/streams/destroy.js:82:8)
May 18 10:44:47 localhost node[28742]:     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
May 18 10:44:47 localhost node[28742]:     at process._tickCallback (internal/process/next_tick.js:63:19)
May 18 10:44:47 localhost systemd[1]: duocun-api.service: Main process exited, code=exited, status=1/FAILURE
May 18 10:44:47 localhost systemd[1]: duocun-api.service: Unit entered failed state.
May 18 10:44:47 localhost systemd[1]: duocun-api.service: Failed with result 'exit-code'.
```

**Comment by bravemaster619** [comment]
Close due to inactivity
